// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "开发者",
            "email": "dev@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/greeter/say-hello": {
            "post": {
                "description": "向指定用户发送问候消息，返回问候语和访问计数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "greeter"
                ],
                "summary": "发送问候",
                "parameters": [
                    {
                        "description": "问候请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/go-api-template_internal_server_dto.SayHelloRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/go-api-template_internal_server_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/go-api-template_api_helloworld_v1.SayHelloResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/go-api-template_internal_server_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务内部错误",
                        "schema": {
                            "$ref": "#/definitions/go-api-template_internal_server_response.Response"
                        }
                    }
                }
            }
        },
        "/greeter/say-hello/{name}": {
            "get": {
                "description": "通过 URL 路径参数向指定用户发送问候消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "greeter"
                ],
                "summary": "发送问候（URL参数）",
                "parameters": [
                    {
                        "maxLength": 100,
                        "minLength": 1,
                        "type": "string",
                        "description": "用户名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/go-api-template_internal_server_response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/go-api-template_api_helloworld_v1.SayHelloResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/go-api-template_internal_server_response.Response"
                        }
                    },
                    "500": {
                        "description": "服务内部错误",
                        "schema": {
                            "$ref": "#/definitions/go-api-template_internal_server_response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "go-api-template_api_helloworld_v1.SayHelloResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "问候消息",
                    "type": "string"
                }
            }
        },
        "go-api-template_internal_pkg_apperrors.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "description": "字段名（JSON 格式）",
                    "type": "string"
                },
                "message": {
                    "description": "错误描述",
                    "type": "string"
                }
            }
        },
        "go-api-template_internal_pkg_reason.Reason": {
            "type": "string",
            "enum": [
                "SUCCESS",
                "INVALID_PARAMS",
                "UNAUTHORIZED",
                "FORBIDDEN",
                "NOT_FOUND",
                "INTERNAL_ERROR",
                "SERVICE_UNAVAILABLE"
            ],
            "x-enum-varnames": [
                "Success",
                "InvalidParams",
                "Unauthorized",
                "Forbidden",
                "NotFound",
                "InternalError",
                "ServiceUnavailable"
            ]
        },
        "go-api-template_internal_server_dto.SayHelloRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "name": {
                    "description": "Name 要问候的用户名称\nrequired: 必填\nmin=1: 最小长度 1\nmax=100: 最大长度 100",
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1,
                    "example": "World"
                }
            }
        },
        "go-api-template_internal_server_response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码",
                    "allOf": [
                        {
                            "$ref": "#/definitions/go-api-template_internal_pkg_reason.Reason"
                        }
                    ]
                },
                "data": {
                    "description": "成功时的数据"
                },
                "details": {
                    "description": "失败时的字段错误详情",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/go-api-template_internal_pkg_apperrors.FieldError"
                    }
                },
                "http_code": {
                    "description": "HTTP 状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "状态消息",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "输入格式: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Go API Template",
	Description:      "一个基于整洁架构的 Go API 服务模板，用于学习和实践 Go Web 开发",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
