// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go-api-template/internal/biz"
	"go-api-template/internal/conf"
	"go-api-template/internal/data"
	"go-api-template/internal/server"
	"go-api-template/internal/service"
)

// Injectors from wire.go:

// wireApp 是 Wire 的注入器函数（Injector）
// Wire 会分析这个函数，根据 ProviderSet 中的构造函数自动生成依赖组装代码
//
// 函数签名说明：
// - 参数：*conf.Config 由 main 加载后传入
// - 返回值：*server.HTTPServer 封装了 Gin 引擎和配置
// - 函数体：调用 wire.Build 并传入所有 ProviderSet
func wireApp(c *conf.Config) (*server.HTTPServer, error) {
	dataData, err := data.NewData(c)
	if err != nil {
		return nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	httpServer := server.NewHTTPServer(c, greeterService)
	return httpServer, nil
}
