// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"go-api-template/internal/biz"
	"go-api-template/internal/data"
	"go-api-template/internal/server"
	"go-api-template/internal/service"
)

// Injectors from wire.go:

// wireApp 是 Wire 的注入器函数（Injector）
// Wire 会分析这个函数，根据 ProviderSet 中的构造函数自动生成依赖组装代码
//
// 函数签名说明：
// - 返回值：最终需要的依赖（*gin.Engine）和可能的错误
// - 函数体：调用 wire.Build 并传入所有 ProviderSet
// - panic：占位符，Wire 生成代码后会被替换
func wireApp() (*gin.Engine, error) {
	dataData, err := data.NewData()
	if err != nil {
		return nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo)
	greeterService := service.NewGreeterService(greeterUsecase)
	engine := server.NewHTTPServer(greeterService)
	return engine, nil
}
